version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: quickcart_db
    environment:
      POSTGRES_DB: quickcart_db
      POSTGRES_USER: quickcart_user
      POSTGRES_PASSWORD: quickcart_password
    ports:
      - '5432:5432'
    volumes:
      - quickcart_db_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  quickcart_db_data:
    driver: local
